const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '../images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Womens Pink Blouse',
            category: 'Shirts',
            image: '../images/p3.jpg',
            price: 40,
            countInStock: 2,
            brand: 'Offbrand',
            rating: 5.0,
            numReviews: 23,
            description: 'beautiful and pink',
        },
        {
            _id: '3',
            name: 'Brown Jacket',
            category: 'Shirts',
            image: '../images/p2.jpg',
            price: 150,
            countInStock: 2,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 230,
            description: 'high quality product',
        },

        {
            _id: '4',
            name: 'Adidas Sweats',
            category: 'Pants',
            image: '../images/p6.jpg',
            price: 110,
            countInStock: 0,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 3,
            description: 'high quality product',
        },
    ],
};

export default data;